@startdot
digraph dependencies {
  node        [style=rounded];

  core        [shape=box, label="1. miragesql", style=filled];
  test        [shape=box, label="2. miragesql-test"];
  tools       [shape=box, label="3. miragesql-tools"];
  integration [shape=box, label="4. miragesql-integration"];

  test        -> core
  tools       -> core
  integration -> core
  integration -> test

  subgraph languages {
    label = "languages"
    scala   [shape=box, label="5. mirage-scala", style=filled, color=lightgray];
    groovy  [shape=box, label="6. mirage-groovy", style=filled, color=lightgray];
    clojure [shape=box, label="7. mirage-clojure", style=filled, color=lightgray];
  }

  scala       -> core;
  scala       -> test;
  groovy      -> core;
  groovy      -> test;
  clojure     -> core;
  clojure     -> test;

}
@enddot